#!/bin/bash
set -e

DEPLOY_DIR="/home/ubuntu/deploy"
ENV_FILE="$DEPLOY_DIR/.env"
IMAGE_INFO_FILE="$DEPLOY_DIR/image-uri.txt"
CONTAINER_NAME="ai-server"
REGION="ap-northeast-2"
SSM_PATH="/commitme/v2/prod/ai-server"

echo "Reading image info from $IMAGE_INFO_FILE..."
if [ ! -f "$IMAGE_INFO_FILE" ]; then
    echo "Error: $IMAGE_INFO_FILE not found!"
    exit 1
fi

IMAGE_URI=$(cat "$IMAGE_INFO_FILE" | tr -d '[:space:]')
echo "Target Image: $IMAGE_URI"

# 1. Login to ECR
echo "Logging in to ECR..."
# Extract registry URL from IMAGE_URI (everything before the first slash)
REGISTRY_URL=$(echo "$IMAGE_URI" | cut -d'/' -f1)
aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin "$REGISTRY_URL"

# 2. Fetch Parameters from SSM Parameter Store
echo "Fetching parameters from separate SSM path: $SSM_PATH"
# We need to fetch all parameters under the path and format them as KEY=VALUE
# `aws ssm get-parameters-by-path` returns JSON. We can parse it with jq if available, or python, or generic text processing.
# Assuming aws cli is installed.
# We will overwrite .env file.

echo "# Generated by CodeDeploy" > "$ENV_FILE"

# Using --with-decryption to get SecureString values
# Querying recursively just in case, though usually flat structure is preferred for .env
# Fetch parameters in JSON format
echo "Fetching parameters from $SSM_PATH..."
params_json=$(aws ssm get-parameters-by-path --path "$SSM_PATH" --recursive --with-decryption --region "$REGION" --output json)

if [ -z "$params_json" ]; then
    echo "Warning: No parameters found at $SSM_PATH"
else
    # Use jq to parse JSON and generate .env content
    echo "$params_json" | jq -r '.Parameters[] | .Name + "=" + .Value' | while read line; do
        # Extract key from full path (e.g., /commitme/v1/prod/DB_HOST -> DB_HOST)
        key=$(echo "$line" | cut -d'=' -f1 | awk -F'/' '{print $NF}')
        value=$(echo "$line" | cut -d'=' -f2-)
        echo "$key=$value" >> "$ENV_FILE"
    done
fi

echo "Environment variables loaded into $ENV_FILE"

# 3. Fetch config.alloy from SSM Parameter Store
ALLOY_CONFIG_DIR="$DEPLOY_DIR/alloy"
ALLOY_CONFIG_FILE="$ALLOY_CONFIG_DIR/config.alloy"
ALLOY_SSM_PARAM="$SSM_PATH/alloy-config"

echo "Fetching Alloy config from SSM: $ALLOY_SSM_PARAM..."
mkdir -p "$ALLOY_CONFIG_DIR"
aws ssm get-parameter \
    --name "$ALLOY_SSM_PARAM" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "$REGION" > "$ALLOY_CONFIG_FILE"

if [ ! -s "$ALLOY_CONFIG_FILE" ]; then
    echo "Error: Failed to fetch Alloy config from SSM!"
    exit 1
fi
echo "Alloy config saved to $ALLOY_CONFIG_FILE"

# 4. Pull Docker Image
echo "Pulling image..."
docker pull "$IMAGE_URI"

# 5. Run Containers with docker compose
echo "Starting containers..."
# Export IMAGE_URI so docker compose can use it
export IMAGE_URI="$IMAGE_URI"

cd "$DEPLOY_DIR"
docker compose up -d

echo "Containers started successfully."
